"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { ActivationPayload } from "@/lib/api-v2";
import type { RegionId } from "@shared/types";
import { DemoModeBanner } from "@/components/DemoModeBanner";

// Same dynamic import pattern as /single — R3F touches browser globals
// during mount, so SSR has to be off. The placeholder mirrors the colour
// of the single-page idle background so the swap-in isn't jarring.
const BrainMeshLazy = dynamic(
  () =>
    import("@/components/brain/BrainMesh").then((mod) => ({
      default: mod.BrainMesh,
    })),
  {
    ssr: false,
    loading: () => (
      <div
        aria-hidden
        className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(245,165,36,0.05),transparent_60%)]"
      />
    ),
  },
);

// ---------------------------------------------------------------------------
// Manifest contract
//
// `apps/web/public/demo-predictions/index.json` is the authoritative source.
// Generated by `scripts/build_demo_gallery.py` — see that script for the
// rules around real-vs-mock provenance.
// ---------------------------------------------------------------------------

interface GalleryEntry {
  slug: string;
  label: string;
  url: string;
  durationSec: number;
  modelVersion: string;
}

interface GalleryManifest {
  entries: GalleryEntry[];
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

interface ListState {
  kind: "list";
  entries: GalleryEntry[];
}
interface DetailLoadingState {
  kind: "loading-detail";
  entries: GalleryEntry[];
  entry: GalleryEntry;
}
interface DetailState {
  kind: "detail";
  entries: GalleryEntry[];
  entry: GalleryEntry;
  activation: ActivationPayload;
}
interface ErrorState {
  kind: "error";
  message: string;
  entries?: GalleryEntry[];
}
interface InitialState {
  kind: "initial";
}

type Phase =
  | InitialState
  | ListState
  | DetailLoadingState
  | DetailState
  | ErrorState;

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function DemoGalleryPage() {
  const [phase, setPhase] = useState<Phase>({ kind: "initial" });
  const abortRef = useRef<AbortController | null>(null);

  useEffect(() => {
    const controller = new AbortController();
    abortRef.current = controller;
    (async () => {
      try {
        const res = await fetch("/demo-predictions/index.json", {
          signal: controller.signal,
          cache: "force-cache",
        });
        if (!res.ok) {
          throw new Error(`HTTP ${res.status}`);
        }
        const manifest = (await res.json()) as GalleryManifest;
        if (!Array.isArray(manifest.entries)) {
          throw new Error("manifest missing `entries`");
        }
        setPhase({ kind: "list", entries: manifest.entries });
      } catch (err) {
        if (controller.signal.aborted) return;
        setPhase({
          kind: "error",
          message:
            err instanceof Error
              ? `Couldn't load the gallery (${err.message}).`
              : "Couldn't load the gallery.",
        });
      }
    })();
    return () => controller.abort();
  }, []);

  const openEntry = useCallback(
    async (entry: GalleryEntry, entries: GalleryEntry[]) => {
      abortRef.current?.abort();
      const controller = new AbortController();
      abortRef.current = controller;
      setPhase({ kind: "loading-detail", entries, entry });
      try {
        const res = await fetch(`/demo-predictions/${entry.slug}.json`, {
          signal: controller.signal,
          cache: "force-cache",
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const activation = (await res.json()) as ActivationPayload;
        setPhase({ kind: "detail", entries, entry, activation });
      } catch (err) {
        if (controller.signal.aborted) return;
        setPhase({
          kind: "error",
          entries,
          message:
            err instanceof Error
              ? `Couldn't load ${entry.label} (${err.message}).`
              : `Couldn't load ${entry.label}.`,
        });
      }
    },
    [],
  );

  const backToList = useCallback(() => {
    abortRef.current?.abort();
    abortRef.current = null;
    setPhase((p) => {
      if (p.kind === "detail" || p.kind === "loading-detail") {
        return { kind: "list", entries: p.entries };
      }
      if (p.kind === "error" && p.entries) {
        return { kind: "list", entries: p.entries };
      }
      return p;
    });
  }, []);

  return (
    <main className="mx-auto max-w-[1280px] px-8 pb-16 pt-12">
      <DemoModeBanner cta={{ href: "/single", label: "Predict your own clip →" }}>
        These predictions are precomputed and ship with the build — curated
        short clips run through the pipeline in mock mode. Nothing is fetched
        or inferred live.
      </DemoModeBanner>
      <header className="motion-fade-in flex items-baseline justify-between gap-6">
        <div>
          <p className="eyebrow">Demo gallery</p>
          <h1 className="mt-2 font-serif text-[28px] leading-tight tracking-tightish text-ink-50">
            Precomputed brains
          </h1>
          <p className="mt-3 max-w-[64ch] text-[14px] leading-relaxed text-ink-200">
            Curated short-clip predictions you can browse offline. No fetch, no
            inference, no AWS — these JSONs ship with the build.
          </p>
        </div>
        <Link
          href="/single"
          className="font-mono text-[11px] uppercase tracking-[0.08em] text-ink-300 hover:text-accent"
        >
          ← back to single
        </Link>
      </header>

      {(phase.kind === "initial" || phase.kind === "list") && (
        <GridView
          entries={phase.kind === "list" ? phase.entries : null}
          onOpen={(e) => {
            if (phase.kind === "list") openEntry(e, phase.entries);
          }}
        />
      )}

      {(phase.kind === "loading-detail" || phase.kind === "detail") && (
        <DetailView phase={phase} onBack={backToList} />
      )}

      {phase.kind === "error" && (
        <section className="mt-10 border border-accent/40 bg-surface/40 p-6">
          <p className="eyebrow text-accent">Gallery error</p>
          <p className="mt-2 max-w-[60ch] text-[13px] leading-relaxed text-ink-200">
            {phase.message}
          </p>
          {phase.entries && (
            <button
              type="button"
              onClick={backToList}
              className="mt-4 border border-line px-4 py-2 font-mono text-[12px] uppercase tracking-[0.08em] text-ink-200 transition-colors hover:border-accent hover:text-accent"
            >
              Back to gallery
            </button>
          )}
        </section>
      )}
    </main>
  );
}

// ---------------------------------------------------------------------------
// Grid view
// ---------------------------------------------------------------------------

interface GridViewProps {
  entries: GalleryEntry[] | null;
  onOpen: (entry: GalleryEntry) => void;
}

function GridView({ entries, onOpen }: GridViewProps) {
  if (entries === null) {
    return (
      <section
        aria-busy
        className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"
      >
        {[0, 1, 2, 3, 4, 5].map((i) => (
          <div
            key={i}
            className="motion-fade-in h-[112px] animate-pulse border border-line bg-surface/40"
          />
        ))}
      </section>
    );
  }
  if (entries.length === 0) {
    return (
      <p className="mt-10 max-w-[60ch] text-[13px] text-ink-300">
        The manifest is empty. Run{" "}
        <code className="font-mono text-ink-100">
          python scripts/build_demo_gallery.py
        </code>{" "}
        to populate it.
      </p>
    );
  }
  return (
    <section className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {entries.map((entry) => (
        <GalleryCard key={entry.slug} entry={entry} onOpen={onOpen} />
      ))}
    </section>
  );
}

function GalleryCard({
  entry,
  onOpen,
}: {
  entry: GalleryEntry;
  onOpen: (entry: GalleryEntry) => void;
}) {
  // Contract check, matching MockModeBadge + InferenceRun.model_id: a mock
  // backend stamps modelVersion with the "tribe-v2-mock" prefix. (.includes
  // would also match an unrelated substring.)
  const isMock = entry.modelVersion.startsWith("tribe-v2-mock");
  return (
    <button
      type="button"
      onClick={() => onOpen(entry)}
      className={[
        "motion-fade-in group flex h-full flex-col items-start gap-3 border border-line bg-surface/40 p-4 text-left",
        "transition-colors hover:border-accent",
        "focus-visible:border-accent focus-visible:outline-none",
      ].join(" ")}
    >
      <p className="font-serif text-[15px] leading-snug text-ink-50 group-hover:text-accent">
        {entry.label}
      </p>
      <p className="font-mono text-[10px] uppercase tracking-[0.08em] text-ink-400">
        {entry.durationSec.toFixed(1)}s · {isMock ? "mock prediction" : "real prediction"}
      </p>
      <p
        title={entry.modelVersion}
        className="mt-auto truncate font-mono text-[10px] text-ink-400"
      >
        {entry.modelVersion}
      </p>
    </button>
  );
}

// ---------------------------------------------------------------------------
// Detail view
// ---------------------------------------------------------------------------

function DetailView({
  phase,
  onBack,
}: {
  phase: DetailLoadingState | DetailState;
  onBack: () => void;
}) {
  const activation = phase.kind === "detail" ? phase.activation : null;
  return (
    <section className="mt-10 grid gap-8 md:grid-cols-[minmax(0,1fr)_minmax(0,460px)]">
      <div className="relative aspect-[5/4] w-full overflow-hidden border border-line bg-canvas">
        {activation ? (
          <BrainMeshLazy
            activation={meanFromActivation(activation)}
            keyframeVertices={
              activation.byRegion as Record<RegionId, number[]>
            }
            timestamps={activation.timestamps}
            playheadSec={0}
          />
        ) : (
          <BrainMeshLazy activation={0} />
        )}
      </div>

      <div className="flex min-h-full flex-col gap-4 border border-line bg-surface/40 p-6">
        <p className="eyebrow">Demo · {phase.entry.slug}</p>
        <p className="font-serif text-[18px] leading-tight text-ink-50">
          {phase.entry.label}
        </p>
        {activation ? (
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-[12px]">
            <dt className="text-ink-400">Duration</dt>
            <dd className="font-mono tabular-nums text-ink-100">
              {activation.videoDurationSec.toFixed(2)}s
            </dd>
            <dt className="text-ink-400">Timepoints</dt>
            <dd className="font-mono tabular-nums text-ink-100">
              {activation.timestamps.length}
            </dd>
            <dt className="text-ink-400">Model</dt>
            <dd className="font-mono text-ink-100">{activation.modelVersion}</dd>
            <dt className="text-ink-400">Regions</dt>
            <dd className="font-mono tabular-nums text-ink-100">
              {Object.keys(activation.byRegion).length}
            </dd>
          </dl>
        ) : (
          <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-ink-300">
            Loading prediction…
          </p>
        )}
        <p className="text-[12px] leading-relaxed text-ink-300">
          These are precomputed and shipped with the build. Re-generate via{" "}
          <code className="font-mono text-ink-100">
            python scripts/build_demo_gallery.py
          </code>
          .
        </p>
        <button
          type="button"
          onClick={onBack}
          className="mt-auto w-full border border-line px-4 py-2 font-mono text-[12px] uppercase tracking-[0.08em] text-ink-200 transition-colors hover:border-accent hover:text-accent"
        >
          Back to gallery
        </button>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Helpers (mirrors apps/web/app/single/page.tsx)
// ---------------------------------------------------------------------------

function meanFromActivation(a: ActivationPayload): number {
  let sum = 0;
  let count = 0;
  for (const series of Object.values(a.byRegion)) {
    if (series.length === 0) continue;
    sum += series[0] ?? 0;
    count += 1;
  }
  if (count === 0) return 0;
  return Math.max(0, Math.min(1, sum / count));
}
